# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ondřej Profant
author: Ondřej Profant
email: profanto@psp.cz
description: > # this means to ignore newlines until "baseurl:"
  Zápisník pirátského poslance Ondřeje Profanta, který se zaměřuje na opendata a e-government.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kedrigern.github.io" # the base hostname & protocol for your site, e.g. http://example.com
keywords: Ondřej Profant, opendata, opensource, open access, big data, piráti, svoboda, kyberbezpečnost, cyklo, eu, praha, doprava, sněmovna, poslanec, egov
twitter_username: ondrej_profant
github_username:  kedrigern
facebook_username: ondrej.profant
cover_image: /assets/img/design/cover.jpg
img: /assets/img/ondrej-profant.jpg
disqus: profant-eu

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock


paginate_path: "/stranka/:num/"
paginate: 5
